### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by Bloodyline**
Hey i finished the work, with some odd commit history but it's okay ;)

### CODE REVIEW

**Comment by flacours** [comment]
hi again,

i failed the 2 suggestions:

1- here is the content of the resources directory . i don't see any migration
```
08:39 $ ls ./resources/
__init__.py	__init__.pyc	database.sql	fixtures.sql	manager_db.py	manager_db.pyc
```

2- i have tried to execute main.py initdb but i have the following error
8:45 $ python main.py initdb
```/Users/flacoursiere/.pyenv/versions/bloodyline/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
b'Error: near line 1: UNIQUE constraint failed: users.username\n'
```

your code looks valid but i would like to execute it.
thanks

**Comment by Bloodyline** [comment]
Hi ! 
Okay so the project is actually ready to run so you can type
`python main.py run`
and it'll run.
If you want to run a fresh setup you might delete the `./migrations` folder and follow the instructions on the readme.
Also if make sure to check the path to the database `app.config['DATABASE']` on the `./alayatodo/__init__.py` file, if you're on Linux it'll work but if you're on Windows change it to `alayatodo.db`.

Thank you for your feedback and tell me if you need anything else !

**Comment by flacours** [comment]
Thank for the feedback. It work half-way. I still have this error

`'Error: near line 1: no such table: users\nError: near line 6: no such table: todos\n'`

I will look at the code with executing it.

**Comment by Bloodyline** [comment]
Okay sorry my bad sorry i forgot a step !

Firstly i'll explain what was going on. The problem was due to the fact that the tables were discovered by the migration script and ready to migrate but was't migrated. If we follow the steps we can see that it creates a new file containing the database and init it with the migration script metadata table.

So of course to work, you need obvisouly the physical table on the database.

To migrate the new tables just type :
`python migration db upgrade head`
Before the `python main initdb` step to correctly migrate and create the physical tables to the database.

Sorry again and i thank you for your feedback.

**Pull request closed without merging**
